[2025-10-06T02:15:18.997+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-06T02:15:19.005+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Airflow_Lab2_Flask.start_Flask_API manual__2025-10-06T02:15:18.435939+00:00 [queued]>
[2025-10-06T02:15:19.008+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Airflow_Lab2_Flask.start_Flask_API manual__2025-10-06T02:15:18.435939+00:00 [queued]>
[2025-10-06T02:15:19.008+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-06T02:15:19.012+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): start_Flask_API> on 2025-10-06 02:15:18.435939+00:00
[2025-10-06T02:15:19.014+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=292) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-06T02:15:19.014+0000] {standard_task_runner.py:63} INFO - Started process 293 to run task
[2025-10-06T02:15:19.015+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Airflow_Lab2_Flask', 'start_Flask_API', 'manual__2025-10-06T02:15:18.435939+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/Flask_API.py', '--cfg-path', '/tmp/tmp7dbhuqvk']
[2025-10-06T02:15:19.015+0000] {standard_task_runner.py:91} INFO - Job 129: Subtask start_Flask_API
[2025-10-06T02:15:19.031+0000] {task_command.py:426} INFO - Running <TaskInstance: Airflow_Lab2_Flask.start_Flask_API manual__2025-10-06T02:15:18.435939+00:00 [running]> on host 1f6a89bf0e15
[2025-10-06T02:15:19.057+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Airflow_Lab2_Flask' AIRFLOW_CTX_TASK_ID='start_Flask_API' AIRFLOW_CTX_EXECUTION_DATE='2025-10-06T02:15:18.435939+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-06T02:15:18.435939+00:00'
[2025-10-06T02:15:19.057+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-06T02:15:19.064+0000] {logging_mixin.py:188} INFO -  * Serving Flask app 'unusual_prefix_fb1fa9258fa1ad786b4829a3672e98fa2e7542a0_Flask_API'
[2025-10-06T02:15:19.065+0000] {logging_mixin.py:188} INFO -  * Debug mode: off
[2025-10-06T02:15:19.065+0000] {logging_mixin.py:188} WARNING - Address already in use
[2025-10-06T02:15:19.065+0000] {logging_mixin.py:188} WARNING - Port 5555 is in use by another program. Either identify and stop that program, or start the server with a different port.
[2025-10-06T02:15:19.065+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-06T02:15:19.065+0000] {taskinstance.py:2907} ERROR - Task failed due to SystemExit(1)
[2025-10-06T02:15:19.068+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Airflow_Lab2_Flask, task_id=start_Flask_API, run_id=manual__2025-10-06T02:15:18.435939+00:00, execution_date=20251006T021518, start_date=20251006T021519, end_date=20251006T021519
[2025-10-06T02:15:19.072+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 129 for task start_Flask_API (Task failed due to SystemExit(1); 293)
[2025-10-06T02:15:19.116+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-06T02:15:19.123+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-06T02:15:19.124+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
