[2025-10-06T02:15:02.138+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-06T02:15:02.157+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Airflow_Lab2_Flask.start_Flask_API manual__2025-10-04T21:59:28.842227+00:00 [queued]>
[2025-10-06T02:15:02.162+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Airflow_Lab2_Flask.start_Flask_API manual__2025-10-04T21:59:28.842227+00:00 [queued]>
[2025-10-06T02:15:02.163+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-06T02:15:02.184+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): start_Flask_API> on 2025-10-04 21:59:28.842227+00:00
[2025-10-06T02:15:02.192+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=158) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-06T02:15:02.195+0000] {standard_task_runner.py:63} INFO - Started process 173 to run task
[2025-10-06T02:15:02.201+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Airflow_Lab2_Flask', 'start_Flask_API', 'manual__2025-10-04T21:59:28.842227+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/Flask_API.py', '--cfg-path', '/tmp/tmp_mrkhi42']
[2025-10-06T02:15:02.208+0000] {standard_task_runner.py:91} INFO - Job 119: Subtask start_Flask_API
[2025-10-06T02:15:02.294+0000] {task_command.py:426} INFO - Running <TaskInstance: Airflow_Lab2_Flask.start_Flask_API manual__2025-10-04T21:59:28.842227+00:00 [running]> on host 1f6a89bf0e15
[2025-10-06T02:15:02.397+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Airflow_Lab2_Flask' AIRFLOW_CTX_TASK_ID='start_Flask_API' AIRFLOW_CTX_EXECUTION_DATE='2025-10-04T21:59:28.842227+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-04T21:59:28.842227+00:00'
[2025-10-06T02:15:02.398+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-06T02:15:02.432+0000] {logging_mixin.py:188} INFO -  * Serving Flask app 'unusual_prefix_fb1fa9258fa1ad786b4829a3672e98fa2e7542a0_Flask_API'
[2025-10-06T02:15:02.433+0000] {logging_mixin.py:188} INFO -  * Debug mode: off
[2025-10-06T02:15:02.434+0000] {logging_mixin.py:188} WARNING - Address already in use
[2025-10-06T02:15:02.435+0000] {logging_mixin.py:188} WARNING - Port 5555 is in use by another program. Either identify and stop that program, or start the server with a different port.
[2025-10-06T02:15:02.436+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-06T02:15:02.436+0000] {taskinstance.py:2907} ERROR - Task failed due to SystemExit(1)
[2025-10-06T02:15:02.453+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Airflow_Lab2_Flask, task_id=start_Flask_API, run_id=manual__2025-10-04T21:59:28.842227+00:00, execution_date=20251004T215928, start_date=20251006T021502, end_date=20251006T021502
[2025-10-06T02:15:02.470+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 119 for task start_Flask_API (Task failed due to SystemExit(1); 173)
[2025-10-06T02:15:02.505+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-06T02:15:02.521+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-06T02:15:02.523+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
